id: P006663
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG6198
  title: འཚུབ་མ་ཁེར་རྐྱང་།
  author: ''
  volumes:
    e5e98d6f071d43caa7191b9449ac0efd:
      image_group_id: I1KG6232
      title: ''
      volume_number: 1
      total_pages: 290
      base_file: v001.txt
